### ISSUE TITLE
Twitter shut down count API

### ISSUE THREAD

**Issue by samized** [shred/shariff-backend-java#1]
Twitter count() has to be removed:

```
java.io.IOException: HTTP 404: Not Found
    at org.shredzone.shariff.target.JSONTarget.count(JSONTarget.java:37)
    at org.shredzone.shariff.ShariffBackend$2.call(ShariffBackend.java:151)
    at org.shredzone.shariff.ShariffBackend$2.call(ShariffBackend.java:148)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by shred** [comment]
Thank you! I totally forgot about that...
Fixed in v1.1.
